<?php

namespace Database\Seeders;

use App\Models\Menu;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Restaurant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories =
            [
                [
                    'name' => 'Pizza',
                    'restaurant_id' => '1',
                    'status' => 'active',
                ],
                [
                    'name' => 'Paste',
                    'restaurant_id' => '1',
                    'status' => 'active',
                ],
                [
                    'name' => 'Drinks',
                    'restaurant_id' => '1',
                    'status' => 'active',
                ],
                [
                    'name' => 'Garnituri',
                    'restaurant_id' => '1',
                    'status' => 'active',
                ],
                [
                    'name' => 'Desert',
                    'restaurant_id' => '1',
                    'status' => 'active',
                ],
                [
                    'name' => 'Soups',
                    'restaurant_id' => '1',
                    'status' => 'active',
                ],
                [
                    'name' => 'Steaks',
                    'restaurant_id' => '1',
                    'status' => 'active',
                ],
                [
                    'name' => 'Sauces',
                    'restaurant_id' => '1',
                    'status' => 'active',
                ],
            ];
        $products = [
            [
                'id' => '1',
                'name' => 'Pizza margherita',
                'weight' => '460',
                'price' => '15',
                'type' => 'restaurant',
                'special_price' => '',
                'category_id' => '1',
                'description' => 'Pizza margherita, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'pizza-margherita',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '2',
                'name' => 'Pizza Diavola',
                'weight' => '500',
                'price' => '15',
                'type' => 'restaurant',
                'special_price' => '8',
                'category_id' => '1',
                'description' => 'Pizza diavola, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'pizza-diavola',
                'status' => 'out_of_stock',
                'restaurant_id' => '1',
            ],
            [
                'id' => '3',
                'name' => 'Pizza vegan',
                'weight' => '350',
                'price' => '15',
                'type' => 'restaurant',
                'special_price' => '8',
                'category_id' => '1',
                'description' => 'Pizza vegan, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'pizza-vegan',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '4',
                'name' => 'Pizza cheesy',
                'weight' => '750',
                'price' => '15',
                'type' => 'restaurant',
                'special_price' => '8',
                'category_id' => '1',
                'description' => 'Pizza cheesy, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'pizza-cheesy',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '5',
                'name' => 'Paste Carbonara',
                'weight' => '350',
                'price' => '17',
                'type' => 'restaurant',
                'special_price' => '',
                'category_id' => '2',
                'description' => 'Paste Carbonara, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'paste-carbonara',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '6',
                'name' => 'Aglio Olio',
                'weight' => '350',
                'price' => '17',
                'type' => 'restaurant',
                'special_price' => '',
                'category_id' => '2',
                'description' => 'Aglio Olio, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'aglio-olio',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '7',
                'name' => 'Paste Bolognese',
                'weight' => '350',
                'price' => '17',
                'type' => 'restaurant',
                'special_price' => '8',
                'category_id' => '2',
                'description' => 'Paste Bolognese, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'paste-bolognese',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '8',
                'name' => 'Coca Cola',
                'weight' => '350',
                'price' => '17',
                'type' => 'bar',
                'special_price' => '',
                'category_id' => '3',
                'description' => 'Coca Cola, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'coca-cola',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '9',
                'name' => 'Sprite',
                'weight' => '350',
                'price' => '17',
                'type' => 'bar',
                'special_price' => '8',
                'category_id' => '3',
                'description' => 'Sprite, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'sprite',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '10',
                'name' => 'Beef Steak',
                'weight' => '560',
                'price' => '25',
                'type' => 'restaurant',
                'special_price' => '19',
                'category_id' => '7',
                'description' => 'Beef Steak, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'beef-steak',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '11',
                'name' => 'Wagyu Steak',
                'weight' => '560',
                'price' => '25',
                'type' => 'restaurant',
                'special_price' => '19',
                'category_id' => '7',
                'description' => 'Beef Steak, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'wagyu-steak',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '12',
                'name' => 'French Fries',
                'weight' => '300',
                'price' => '8',
                'type' => 'restaurant',
                'special_price' => '3',
                'category_id' => '4',
                'description' => 'French Fries, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'french-fries',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '13',
                'name' => 'Roasted Potatoes',
                'weight' => '400',
                'price' => '12',
                'type' => 'restaurant',
                'special_price' => '8',
                'category_id' => '4',
                'description' => 'Roasted Potatoes, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'roasted-potatoes',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '14',
                'name' => 'Tomato Sauce',
                'weight' => '50',
                'price' => '2',
                'type' => 'restaurant',
                'special_price' => '1',
                'category_id' => '8',
                'description' => 'Tomato Sauc, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'tomato-sauce',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '15',
                'name' => 'Mayo Sauce',
                'weight' => '50',
                'price' => '2',
                'type' => 'restaurant',
                'special_price' => '',
                'category_id' => '8',
                'description' => 'Mayo Sauc, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'mayo-sauce',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '16',
                'name' => 'Hot Sauce',
                'weight' => '50',
                'price' => '2',
                'type' => 'restaurant',
                'special_price' => '1',
                'category_id' => '8',
                'description' => 'Hot Sauce, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'hot-sauce',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '17',
                'name' => 'Tomato & Basil Soup',
                'weight' => '500',
                'price' => '5',
                'type' => 'restaurant',
                'special_price' => '3',
                'category_id' => '6',
                'description' => 'Tomato & Basil, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'tomato-basil',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '18',
                'name' => 'Mushroom Soup',
                'weight' => '505',
                'price' => '2',
                'type' => 'restaurant',
                'special_price' => '',
                'category_id' => '6',
                'description' => 'Mushroom Soup, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'mushroom-soup',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '19',
                'name' => 'Chicken Soup',
                'weight' => '510',
                'price' => '5',
                'type' => 'restaurant',
                'special_price' => '2',
                'category_id' => '6',
                'description' => 'Chicken Soup, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'chicken-soup',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '20',
                'name' => 'Swiss Roll',
                'weight' => '350',
                'price' => '10',
                'type' => 'restaurant',
                'special_price' => '',
                'category_id' => '5',
                'description' => 'Swiss Roll, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'swiss-roll',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '21',
                'name' => 'Cheesecake',
                'weight' => '350',
                'price' => '10',
                'type' => 'restaurant',
                'special_price' => '3',
                'category_id' => '5',
                'description' => 'Cheesecake, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'cheesecake',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
            [
                'id' => '22',
                'name' => 'Cupcake',
                'weight' => '350',
                'price' => '10',
                'type' => 'restaurant',
                'special_price' => '3',
                'category_id' => '5',
                'description' => 'Cupcake, as the Italians call it, is a simple pizza hailing from Naples. When done right, margherita pizza features a bubbly crust, crushed San Marzano tomato sauce, fresh mozzarella and basil',
                'slug' => 'cupcake',
                'status' => 'available',
                'restaurant_id' => '1',
            ],
        ];
        foreach ($categories as $key => $cat) {
            ProductCategory::create([
                'name' => $cat['name'],
                'restaurant_id' => $cat['restaurant_id'],
                'status' => $cat['status'],
                'order' => $key + 1,
            ]);
        }
        foreach ($products as $product) {
            Product::create([
                'id' => $product['id'],
                'name' => $product['name'],
                'weight' => $product['weight'],
                'price' => $product['price'],
                'type' => $product['type'],
                'special_price' => $product['special_price'],
                'description' => $product['description'],
                'slug' => $product['slug'],
                'status' => $product['status'],
                'restaurant_id' => $product['restaurant_id'],
            ]);

            DB::table('product_to_category')->insert([
                'product_id' => $product['id'],
                'category_id' => $product['category_id'],
                'order' => $product['id'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
        for ($i = 1; $i <= Restaurant::count(); $i++) {
            Menu::create([
                'title' => 'Menu',
                'restaurant_id' => $i,
            ]);
        }
    }
}
