version: "3"

http:
  address: 0.0.0.0:8000
  middleware: ["static", "gzip"]

  static:
    dir: "public"
    forbid: [".php", ".htaccess"]
    headers:
      cache-control: "public, max-age=31536000, immutable"
