version: "3"

rpc:
  listen: "tcp://127.0.0.1:6001"

server:
  command: "php artisan octane:start --server=roadrunner --host=127.0.0.1 --port=8000"

http:
  address: 0.0.0.0:8000
  middleware: ["static", "gzip"]

  static:
    dir: "public"
    forbid: [".php", ".htaccess"]
    headers:
      cache-control: "public, max-age=31536000, immutable"
